# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
baseurl:        ""
url:            "https://lornus.me"
exclude:
  - .git/
  - .github/
  - Gemfile
  - README.md
