# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
baseurl:        ""
url:            "http://owlzone.org"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - Gemfile
  - README.md

# Plugins
plugins:
  - jekyll-paginate

# Social
title:              OwlZone
description:        "The reign of a night owl."

# Url
category_dir: category/
tag_dir: tag/

# Image
header-image: assets/img/owl-and-rat.jpg

# Excerpt
excerpt_separator: "\n\n\n\n"

# Paginate
paginate: 5
