# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
baseurl:        ""
url:            "https://mapkts.com"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - src/
  - node_modules/
  - Gemfile
  - README.md

# Plugins
plugins:
  - jekyll-paginate

# Social
title:           OwlZone
description:     "The Reign of a Night Owl"

# Url
category_dir: categories/
tag_dir: tags/

# Image
header-image: assets/img/owl-and-rat.jpg

# Excerpt
excerpt_separator: "\n\n\n\n"
